# Project: lab21
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = lab21_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/Dev_C++/Dev-Cpp/MinGW64/lib" -L"D:/Dev_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev_C++/Dev-Cpp/MinGW64/include" -I"D:/Dev_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev_C++/Dev-Cpp/MinGW64/include" -I"D:/Dev_C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev_C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = lab21.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

lab21_private.res: lab21_private.rc 
	$(WINDRES) -i lab21_private.rc --input-format=rc -o lab21_private.res -O coff 

